### ISSUE TITLE
Causing a panic by accessing arr out of range doesn't pass the test

### ISSUE THREAD

**Issue by tom7980** [crazymykl/rust-koans#39]
I've been running through the koans today and came across an issue with the array out_of_index Koan. If I try to access an arr index that is out of bounds instead of passing the test I am presented with this error.
```
error: index out of bounds: the len is 5 but the index is 5
  --> src/koans/array.rs:25:5
   |
25 |     arr[5];
   |     ^^^^^^
   |
   = note: #[deny(const_err)] on by default

error: aborting due to previous error
```

In order to get the test to pass I have to call a panic! myself like this

```
#[test]
#[should_panic]
fn out_of_index() {
    let arr: [&'static str; 5] = ["rust", "is", "mostly", "for", "nerds"];
    panic!("panic");
}
```

It might just be I'm doing it wrong, or my rust version as I am running 1.29.0, or of course the #[deny(const_err)] config but I thought I'd bring it up.

Sorry if this is in the wrong place!

**Comment by crazymykl** [comment]
You're correct. They added a lint to catch this common error in the time since the koans were written. When I do the 2018 edition update, I will re-work this one. Thanks for the report!

**Comment by crd477** [comment]
Thanks to a tip from @shepmaster, the solution I used was:
```
    let i = 5;
    arr[i];
```

**Comment by brianm** [comment]
I thought it was a clever test used to find the limits of the linter. That is, "how do you force a panic?"

**Comment by samhattangady** [comment]
I ended up using
```
arr[arr.len()];
```

That worked too.

**Comment by tom7980** [comment]
Looks like this issue has been fixed in a recent update so I'll close the issue, thanks for everyone's input!

**Comment by palerdot** [comment]
FYI, this is still an issue with latest rust release `rustc 1.34.2 (6c2484dc3 2019-05-13)`

**Comment by szenadam** [comment]
FYI#2, it is still an issue with:`rustc 1.51.0 (2fd73fabe 2021-03-23)`

@samhattangady's method worked for me as well: https://github.com/crazymykl/rust-koans/issues/39#issuecomment-473829456
